If iptables-save isn't available then assume that no rules are active
The command 'iptables-save' is marked as being an optional command
so the provider shouldn't produce error messages when it is missing

Resolves the following error message which occurs when iptables-save is
not installed on the system yet and resources { 'firewall': purge => true }
  Error: /Stage[main]/Fw/Resources[firewall]: Failed to generate additional resources using 'generate': Command iptables_save is missing