ensure that /etc/sysconfig/iptables exists
The iptables service will not start if /etc/sysconfig/iptables is
missing.  Attempting to start the service without this file will result
in:

ERROR : Error appeared during Puppet run: 172.16.0.14_prescript.pp
Error: Could not start Service[iptables]: Execution of '/sbin/service
iptables start' returned 6:

This patch ensures the file exists before starting the iptables service.